[PHP]
extension_dir = "D:\eternalglow-local\bin\php\ext"
extension=curl
extension=exif
extension=fileinfo
extension=gd
extension=gettext
extension=intl
extension=mbstring
extension=mysqli
extension=openssl
extension=pdo_mysql
extension=sodium
extension=zip
zend_extension=opcache

opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.max_accelerated_files=20000
opcache.validate_timestamps=1
opcache.revalidate_freq=2
realpath_cache_size=4096K
realpath_cache_ttl=600

memory_limit=512M
max_execution_time=300
max_input_time=300
max_input_vars=5000
upload_max_filesize=128M
post_max_size=128M
output_buffering=4096

error_reporting=E_ALL & ~E_DEPRECATED & ~E_STRICT
display_errors=Off
log_errors=On
error_log="C:\Users\Ake\Downloads\eternalglow\local-env\logs\php-error.log"

date.timezone=America/Mexico_City
default_charset="UTF-8"
allow_url_fopen=On
curl.cainfo="C:\Users\Ake\Downloads\eternalglow\u355783479.eternalglow-com-mx.20260922005336\domains\eternalglow.com.mx\public_html\wp-includes\certificates\ca-bundle.crt"
openssl.cafile="C:\Users\Ake\Downloads\eternalglow\u355783479.eternalglow-com-mx.20260922005336\domains\eternalglow.com.mx\public_html\wp-includes\certificates\ca-bundle.crt"

; Temporales en D: (C: est? casi lleno)
sys_temp_dir="D:/eternalglow-local/tmp"
upload_tmp_dir="D:/eternalglow-local/tmp"
session.save_path="D:/eternalglow-local/tmp"
